### ISSUE TITLE
Crash in Sketch v39

### ISSUE THREAD

**Issue by bomberstudios** [edenvidal/States#10]
Plugin crashes In [Sketch v39 Beta](http://sketchapp.com/beta/)

Steps:
- Create a new document
- Insert an Artboard
- Select Plugins › Show States
- Right click the States window and select 'Create Page'. Sketch v39 crashes.

FTR, this only happens when using the contextual menu, clicking the '+' icon seems to work fine.

**Comment by rodionovd** [comment]
Hello @bomberstudios! Your very detailed report is deeply appreciated ❤️

Please, try this (attached) new version and let us now if it works for you on 3.9beta

Thanks!

▶️ [States-beta-fix.0.99.sketchplugin.zip](https://github.com/edenvidal/States/files/357413/States-beta-fix.0.99.sketchplugin.zip)

**Comment by bomberstudios** [comment]
Works like a charm here : )
