### ISSUE TITLE
"States" panel doesn't appear anywhere

### ISSUE THREAD

**Issue by tthompsonIMS** [edenvidal/States#3]
Unsure why this is happening. I have added **States.sketchplugin** to my Sketch plugins folder but when I select _States_ from the Plugin dropdown, this is what I see...

![screen shot 2016-06-21 at 1 27 51 pm](https://cloud.githubusercontent.com/assets/20074868/16245072/012d55da-37b4-11e6-8fe2-e0e872f1d21b.png)

Nothing. No options or objects. The _States_ panel that you mention doesn't show up...at least not anywhere I can see it. When I go to look for it under the _Manage Plugins_ command, it doesn't show up...

![screen shot 2016-06-21 at 1 34 05 pm](https://cloud.githubusercontent.com/assets/20074868/16245263/dccdf7de-37b4-11e6-9af0-ce63905be9e8.png)

Would love to use this but I'm unsure of how to proceed.

**Comment by edenvidal** [comment]
Hey, In what version of the OS / Sketch you are using?

**Comment by tthompsonIMS** [comment]
Thanks for the quick reply.

OS: El Capitan v10.11.5

Sketch: v3.8.3 (29802)

**Comment by tthompsonIMS** [comment]
This problem seems to have cleared up when I was able to use **Sketch Toolbox** to install the plugin. Instead of doing it manually. Most likely operator error. Thanks again for the quick reply.
