### ISSUE TITLE
Feature Request: Export from the States panel

### ISSUE THREAD

**Issue by tthompsonIMS** [edenvidal/States#4]
Thinking in terms of Photoshop, there is an option to export Layer Comps as individual files. Would be very useful to be able to do the same from the States panel. You've provided the ability to individually name the states there...so it would also be useful to export using those names as the filenames.

Thanks!

**Comment by edenvidal** [comment]
Hey Todd,
True, exporting will be awesome and I will probably put it later on. For
now you can export the states to a new page and export them from there.

Best

On Thu, Jun 23, 2016 at 3:53 AM, Todd Thompson notifications@github.com
wrote:

> Thinking in terms of Photoshop, there is an option to export Layer Comps
> as individual files. Would be very useful to be able to do the same from
> the States panel. You've provided the ability to individually name the
> states there...so it would also be useful to export using those names as
> the filenames.
> 
> Thanks!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/edenvidal/States/issues/4, or mute the thread
> https://github.com/notifications/unsubscribe/AMzAeAceoKoCb3ifUcqrqSUwaKxbZfpRks5qOdjxgaJpZM4I8W-q
> .

## 

Eden Vidal
xpos.it
fullstack.design
edenvidal.com

**Comment by tthompsonIMS** [comment]
To be clear (because I don't think I was), I'm talking about a batch process as opposed to a one-at-a-time export. But thanks again for the quick reply. Finding **States** to be an _invaluable_ part of Sketch.

**Comment by edenvidal** [comment]
Wow, I should add it as a testimonial! I think you are right, States have a
lot of potential to become extremely useful tool in the workflow. I'm going
through the feedback right now and probably go for another version soon.

On Thu, Jun 23, 2016 at 9:17 PM, Todd Thompson notifications@github.com
wrote:

> To be clear (because I don't think I was), I'm talking about a batch
> process as opposed to a one-at-a-time export. But thanks again for the
> quick reply. Finding _States_ to be an _invaluable_ part of Sketch.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> https://github.com/edenvidal/States/issues/4#issuecomment-228137060, or mute
> the thread
> https://github.com/notifications/unsubscribe/AMzAeIwdAzEJmcFR5dFkUbkCLYLZjbFwks5qOs2igaJpZM4I8W-q
> .

## 

Eden Vidal
xpos.it
fullstack.design
edenvidal.com

**Comment by tthompsonIMS** [comment]
Hey man....feel free to quote me. I'm a believer.
